apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-cert
  namespace: istio-system
spec:
  secretName: nginx-test-cert
  commonName: nginx.jameselgar.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - nginx.jameselgar.com
